### PR TITLE
Example using WEC-Sim data with mhkit-matlab

### PR DESCRIPTION
**Pull request by kmruehl**
**PR for MHKiT-MATLAB Example using WEC-Sim Data**

This PR, but is for a MATLAB Live example to load WEC-Sim data and apply MHKiT functions. I did not make it a 1:1 to the [MHKiT-Python WEC-Sim example](https://mhkit-software.github.io/MHKiT/wecsim_example.html#) since this example is largely using native MATLAB functions. But I did make it as close as possible for the examples provided. @rpauly18 This is ready for review.

### CODE REVIEW

**Comment by rpauly18** [comment]
@kmruehl Thanks for pulling this together. I am curious what version of MATLAB you used to pull this together. When I run it, the data is not loading as it should. I get a warning that the data cannot be loaded as an object and is instead is read as a uint32, which is essentially useless. I am going to keep trying to mess around with how it is loaded.

**Comment by kmruehl** [comment]
@rpauly18 that is very strange. I'm running this example in 2020a. Since this example includes a WEC-Sim output object, I went ahead and changed it to a structure. Hopefully this will resolve your issue. Also, we are considering making the default output of WEC-Sim a structure instead of an object anyway. That should solve the issue universally (for matlab and python). https://github.com/WEC-Sim/WEC-Sim/projects/37

**Review by rpauly18 — APPROVED** [review]
Looks great, Kelley. Thanks!

**Comment by kmruehl** [comment]
@rpauly18 I'm glad that resolved the issue. I'm going to delete this branch now.

**Pull request merged**
