### PR TITLE
Add `method` option to `surface_elevation`

### PR DESCRIPTION
**Pull request by simmsa**
In [MHKiT-Python #250](https://github.com/MHKiT-Software/MHKiT-Python/pull/250) a method option was added to `wave.resource.surface_elevation`. This exposes that option to the MHKiT-MATLAB user.

### CODE REVIEW

**Comment by simmsa** [comment]
List of changes:

1. Add method option to surface elevation
2. Add test to to verify that the method option gets passed to python and the results for each method match each other
3. Get tests working using findings from delft-3d-io branch
4. Update plugin version to 0.4.1.1
5. Update binary

**Comment by simmsa** [comment]
@rpauly18 or @hivanov-nrel, this is ready for review when either of you have time. I would like to get this into master before we merge Delft3D functionality.

**Review by rpauly18 — APPROVED** [review]
Hi Andrew, from a technical standpoint, this looks fine. Some of the tests are failing on my local machine which was trying to resolve before approving, but since they are passing in GitHub, it's probably something in my local MHKiT Matlab install.

**Comment by simmsa** [comment]
@rpauly18, thanks for reviewing! The new version of MHKiT-Python is introducing some new bugs for us. I am tracking them in #130. My best guess is your test failures are related similar to the ones introduced by v0.8.0. I am going to go ahead and merge this.

**Pull request merged**
