### PR TITLE
adding vecto_channels to get_stats

### PR DESCRIPTION
**Pull request by rpauly18**
Corresponding PR to https://github.com/MHKiT-Software/MHKiT-Python/pull/94

### CODE REVIEW

**Comment by rpauly18** [comment]
@mfaltas-sandia and @kmruehl I am hoping you can help me diagnose an issue. I am working on this PR but the CI tests do not appear to be triggering. Do you have any thoughts as to why?

**Comment by mfaltas-sandia** [comment]
Hi @rpauly18 , the builds look to be triggering; they are just not appearing as a check mark or a cross. I am not sure why. 
You can take a look at the build requests here: https://travis-ci.org/github/MHKiT-Software/MHKiT-MATLAB/requests

image

Clicking on that link gives you the image above. If you look at request 26 and 27, you see your two commits "restarting test" and "Merge branch ....". Right next to that on the far right, it says "Build created successfully". 

If you click on the number of the build #26 or #27 then this will take you to the build that was triggered by your commit. For convenience, here is the build triggered by "restarting test" https://travis-ci.org/github/MHKiT-Software/MHKiT-MATLAB/builds/768126570 and here is the build triggered by "Merge branch...": https://travis-ci.org/github/MHKiT-Software/MHKiT-MATLAB/builds/768127292
The time of the builds also checks out as the builds were both triggered about an hour ago.

Digging deeper, I clicked on the GitHub commit referenced in the Travis Build. I am not sure it is your same commit. I am still looking into it.

**Comment by rpauly18** [comment]
Thanks @mfaltas-sandia. The same thing has started occurring on the Python side as well. Guessing something changed in Travis or Github.

**Comment by mfaltas-sandia** [comment]
@rpauly18 I am not sure if it could be related but try to look at the number of credits left on the account. I don't think this is related because it shows that "Build created successfully" but I suppose it is safer to check anyways. Negative credit could result in builds not triggering.

To check the number of credits, click on the account avatar on the top right of the Travis CI page, then click  on settings, then click on plan.

**Comment by rpauly18** [comment]
I do not see an option to check credits. It could be that my account is not set up to see that info.

**Review by hivanov-nrel — APPROVED** [review]
Looks pretty good to me.

**Pull request merged**
