### PR TITLE
V0.3.0 MHKiT

### PR DESCRIPTION
**Pull request by rpauly18**
This PR contains the new functions and reorganizations for MHKiT v0.3.0. 

Still to-do: Tests for all new functions

### CODE REVIEW

**Comment by rpauly18** [comment]
@kmruehl and @ssolson I still need to develop the tests for these new functions, but they are ready to be reviewed, particularly for the DocString information. Thanks!

**Comment by ssolson** [comment]
I think you have the loads functions at both the loads level and the sub folder level:
image

**Comment by ssolson** [comment]
It looks like there is still a test data folder. Is your plan to move all of this to example data when you write the tests?

image

**Comment by rpauly18** [comment]
Yes, I am working on that as we speak.

**Comment by kmruehl** [comment]
@rpauly18 do you mean that you would like me to check the API documentation?

**Comment by rpauly18** [comment]
@kmruehl yes, or at least do a general proof read. If you have time, it would also be good for you to run some of the functions and/or the example notebooks. Thanks!

**Comment by ssolson** [comment]
Rebecca to be consistient with python the wave.io folder should have a subfolder called NDBC and then each function would be request data etc. Is this possible/ does it make sense in MATLAB?
image

Also will you be able to wrap the WEC-SIM IO? I don't expect it to change in structure at this point.

**Comment by rpauly18** [comment]
@ssolson I will not be wrapping the WEC-Sim IO because WEC-Sim data is already in a MATLAB friendly format, so wrapping the Python function would be necessary. 

I could create the sub folder for NDBC, but at this point it would be the only folder in IO, so it might not be necessary.

**Comment by rpauly18** [comment]
That being said, it would be useful to develop a WEC-Sim example notebook.

**Comment by ssolson** [comment]
Of course that makes sense to not wrap it! Agreed on the notebook/ testing the WEC-SIM Matlab data to MHKiT functions.

I would be in favor of creating the NDBC subfolder as we plan to at least add Aiden's work in the future and then the NDBC functionality would remain consisteient e.g. no rework of the examples/ tests and documentation. But its your call.

**Comment by ssolson** [comment]
Rebecca I am getting this error below when I try to run the contour notebook example:
image

I would change the title of section 3 to something like "Find the 100 year contour line " (this should eventually be changed on the Python side too)

line 18 on the definition of period needs semicolon to close the line.

**Comment by rpauly18** [comment]
Sterling, what version of Matlab do you have? I do not get that error. @kmruehl can you try running the example ad see if you also get the error?

**Comment by ssolson** [comment]
'9.8.0.1417392 (R2020a) Update 4'

**Comment by rpauly18** [comment]
OK, I really hope MATLAB did not do away with converting numpy to double in 2020, because that will mean just about every wrapper in the package will need to be changed. I am still on 2019.

**Comment by kmruehl** [comment]
@rpauly18 I can take a look. I have both 2020s and 2018b on my laptop.

**Comment by rpauly18** [comment]
@ssolson Have you been able to run any of the other examples? Many of the MHKiT-MATLAB functions make that conversion, so it would be good to see if you get the same error in other notebooks.

**Comment by ssolson** [comment]
I'm trying to run but I think  this is missing the other data files?
image

**Comment by ssolson** [comment]
Yes I am getting the error in wave:
image

**Comment by rpauly18** [comment]
@ssolson I made some updates to how numpy arrays are handled in NDBC_request_data. Can try re-running the environmental contours example to see if this methodology will work for you?

**Comment by ssolson** [comment]
Hey Rebecca, I installed the 3.1 toolbox and I am getting the same conversion to double error

**Comment by rpauly18** [comment]
Darn. OK, I am going to wait until Kelley reports back to proceed. I will need to go through NREL IT to get a copy of R2020, so I cannot test it yet myself.

**Comment by kmruehl** [comment]
> 
> 
> That being said, it would be useful to develop a WEC-Sim example notebook.

I already have one I can add, I developed a `*.py `and `*.m` example at the same time.

**Comment by rpauly18** [comment]
Thats great. Thanks, Kelley!

**Comment by kmruehl** [comment]
> 
> 
> OK, I really hope MATLAB did not do away with converting numpy to double in 2020, because that will mean just about every wrapper in the package will need to be changed. I am still on 2019.

I just ran `environmental_contours_example.mlx` in 2020a without issue.

**Comment by ssolson** [comment]
What python version do you guys run? 
I have 3.8.3

**Comment by kmruehl** [comment]
Name: numpy
Version: 1.18.1

Python 3.7.6

**Comment by rpauly18** [comment]
numpy 1.18.5

Python 3.7.5


I thought Python 3.8 might be an issue, but according to this https://www.mathworks.com/help/matlab/matlab_external/system-requirements-for-matlab-engine-for-python.html
it should be fine.

**Comment by rpauly18** [comment]
@ssolson Turns out the issue is Python 3.8. I updated and got the same error. I have now reverted back to 3.7. We will need to think about how to handle this issue.

**Comment by ssolson** [comment]
Super happy we diagnosed the issue. Now I can change the MATLAB instructions to state that it is only compatible with 3.6 and 3.7 as it did before.

Can you switch back to 3.8 and see if you get the WEC SIM io error I was getting on the detrend call?

**Comment by rpauly18** [comment]
@ssolson is there any way you can update to Matlab 2020b? According to Matlab forums, 2020a does not support Python3.8. The first Matlab version to support 3.8 is 2020b.

**Comment by ssolson** [comment]
Yes I am downloading it now. I'll let you know if it fixes the issue.

**Comment by ssolson** [comment]
Updating to 2020b resolved the double conversion issue for Python 3.8

**Comment by rpauly18** [comment]
@ssolson @kmruehl I think this PR is ready for a final review, and hopefully merging.

**Review by ssolson — APPROVED** [review]
All examples run and all tests pass.

**Comment by rpauly18** [comment]
I am going to wait until we tag the Python release on pip before merging, just in case someone tries to download this before they can pip install the corresponding MHKiT-Python.

**Pull request merged**
