### PR TITLE
Dolfyn Functionality: IO and rotations

### PR DESCRIPTION
**Pull request by Alex-McVey**
2 other readers need to be added and then testing set up but it would be good to discuss if this is the direction we want to go in.

### CODE REVIEW

**Review by rpauly18 — COMMENTED** [review]
Overall the direction you are going looks good. Only major comment is that I ask you consider if any of the functions that live within read_nortek.m will be useable for other file types, if so, we will want to pull those out. It is also likely I will want to reorganize where some of the functions live before merging, but we can make those decisions after more content is added. Overall, this looks good at a high level without any formal tests written yet and I think users will find it easy to use read_nortek.m.

**Comment by Alex-McVey** [comment]
My most recent push changed the read time of the read_signature example from 70 minutes to 3 minutes with half of that being in the fread calls. I will continue to look to improve the algorithm but it looks like the 1.5 minutes of fread are baked in (unless we can push them to cuda or something like that)

**Comment by Alex-McVey** [comment]
Updated the call method in dolfyn_read to be compatible with prior Matlab versions (I had option=value instead of 'option',value)

**Comment by hivanov-nrel** [comment]
@Alex-McVey your recent changes worked and i was able to run the examples. However, i am having trouble with some of the tests. It looks like there may be some more MATLAB version compatibility issues. The error i get occurs when trying to read the netcdf files in your tests. 

>Error using netcdf.getVar (line 137)    12 is not a recognized netCDF datatype.

This is directly confined to the tests, but it may be something to consider. If users are saving these files in netCDF format and then trying to read them later, we should make sure that there is backwards compatibility between matlab versions or we should update our requirements.

**Comment by hivanov-nrel** [comment]
@Alex-McVey can you pull the latest commits from the dev branch? This should update github actions to run the R2020b matlab release test on your PR.

**Comment by Alex-McVey** [comment]
Status of Dolfn-matlab as of 9/30
All pushes up to https://github.com/MHKiT-Software/MHKiT-MATLAB/pull/79/commits/903daf1340c1adf08f72847d5498e392395786b0 (The set_coords change to dir did ...) were associated with the original python PR (DOLfYN source code #169 `https://github.com/MHKiT-Software/MHKiT-Python/pull/169`). These pushes are the core of Dolfyn and allow for users to read and write Norteck, signature, and rdi files as well as rotate through the various beam orientations. 

All pushes after are related to the second python Dolfyn PR (PR 186 `https://github.com/MHKiT-Software/MHKiT-Python/pull/186`) 

Functions covered so far by me
- set_range_offset for adp
- find_surface (from pressure) for adp
- nan_beyond_surface for adp
- correlation_filter for adp

The functions I haven't covered are too numerous to list but the files that need to be added are (from python module)
- tools/fft.py
- tools/misc.py (might not need any of these)
- adp/clean.py (many of these functions were part of what I added)
- adv/clean.py
- adv/motion.py
- adv/turbulence.py

I can't say that this is the complete list of items missing but it should be close

**Pull request merged**
