### PR TITLE
WPTO for Matlab

### PR DESCRIPTION
**Pull request by hivanov-nrel**
Created new PR for adding WPTO functionality to MATLAB without using python wrapper. This aims to use the native matlab functions to access the WPTO data from AWS.

### CODE REVIEW

**Comment by rpauly18** [comment]
@hivanov-nrel what method have you been using to essentially log into AWS to access the S3 bucket?

**Comment by hivanov-nrel** [comment]
You can directly read from AWS since there are no login credentials associated. So you should be able to run that script as is. Let me know if thats not the case. The inbuilt matlab function h5read is what i use.

**Comment by rpauly18** [comment]
This also does not work for me in Windows. I still get 
"unable to find file. Ensure file exists and is valid." from h5read in line 21. 

I am guessing you have something set up somewhere creating access to AWS.

**Comment by hivanov-nrel** [comment]
Interesting......i asked Scott Dana to run it and he had the same issue....

I looked up if i had set any environmental variables related to AWS but those came up empty. I was able to reproduce this error when i ran it on my 2018b version of matlab. It works on my 2020b version though. Scott's is 2019a. Ill try to keep digging into what else it might be....

**Comment by rpauly18** [comment]
> Interesting......i asked Scott Dana to run it and he had the same issue....
> 
> I looked up if i had set any environmental variables related to AWS but those came up empty. I was able to reproduce this error when i ran it on my 2018b version of matlab. It works on my 2020b version though. Scott's is 2019a. Ill try to keep digging into what else it might be....

The Matlab version may be the issue. I am using 2020a. Might be worth looking into

**Comment by hivanov-nrel** [comment]
@rpauly18 i got the REST API working with MATLAB. The functionality is great and impressively quick. Next steps for me are to get an example notebook going and also making tests. I think i will try to utilize the same data used on the python side to keep things consistent for validation.

**Comment by rpauly18** [comment]
@hivanov-nrel this looks great. One of the next steps is to develop tests for these functions similar to the tests on the Python side. I can help if need be. 

Another note of interest is that the request for data that is failing on the Python side, works here. There are no obvious differences between the region_selection functions that I can see, but comparing the two might be a good place to start with debugging.

**Comment by hivanov-nrel** [comment]
@rpauly18 thanks Rebecca. I believe there should already be tests made that are similar to the python side. I ended up just adding to the Wave_TestIO.m file. I must have done something wrong but I am not sure what exactly?

**Comment by rpauly18** [comment]
My bad on the tests! I did not see them, must be going blind. I will review tomorrow. Before we merge this PR, we are going to get GitHub Actions set up on this repo so the tests will actually run.

**Comment by rpauly18** [comment]
@hivanov-nrel it looks like you did not commit the .csv files needed for the hindcast tests.

**Comment by hivanov-nrel** [comment]
@rpauly18 just uploaded the data. It looks like .gitignore was set up to ignore csv files which may be why it slipped through the cracks. I updated that text file, but let me know if you foresee that being an issue elsewhere.

**Review by rpauly18 — APPROVED** [review]

**Pull request merged**
