### PR TITLE
Move CI Unit Tests to GitHub Actions

### PR DESCRIPTION
**Pull request by H0R5E**
This PR moves the continuous integration unit tests to GitHub Actions.

There are a number of changes and notes, as follows:

* The `main.yml` workflow was renamed to `unit_tests.yml` to represent its purpose and the TravisCI badge in the README is replaced by the unit tests workflow badge.
* The TravisCI build config (`.travis.yml`) has been removed.
* There was an issue with [MHKiT-Python](https://github.com/MHKiT-Software/MHKiT-Python) and matplotlib compatibility due to [this bug](https://github.com/matplotlib/matplotlib/issues/22378). The matplotlib version was pinned  to `<3.4.2` for now. @ssolson, this might be something that interests you.
* To get around the HDF5 compatibility issue, MATLAB's Python support is set to run in "OutOfProcess" execution mode.
* There are some "gotchas" with the MATLAB support on GitHub actions:
    + Firstly, state isn't saved between steps, so for our case you need to do everything in one call to MATLAB - see the "Create MATLAB batch command" step. Added an issue about this [here](https://github.com/matlab-actions/overview/issues/6).
    + Secondly, MATLAB support on Windows runners is still unofficial and doesn't seem to work with "OutOfProcess" execution mode. Added an issue about this [here](https://github.com/matlab-actions/setup-matlab/issues/26) and disabled testing on Windows runners for now.
* Some of the tests were running extremely slowly, so following some profiling on them it was found that calling `cell` on a Pandas DataFrame DateIndex was very inefficient. The `datetime_index_to_ordinal` function was added to the `mhkit_python_utils.pandas_dataframe` module to convert a DateIndex into MATLAB ordinal dates before converting to a MATLAB native type, which accelerated this step by 100x. See [mhkit/river/IO/read_usgs_file.m](https://github.com/MHKiT-Software/MHKiT-MATLAB/compare/master...H0R5E:github_actions?expand=1#diff-9e956feb1d011536f23046f839c19086cdcd149075cc6a1968d7ad73c0b0b522) for an example of the changes.
* The tests for the `environmental_contour` function were disabled as it is no longer compatible with MHKiT-Python, following [this change](https://github.com/MHKiT-Software/MHKiT-Python/commit/6e4bff06888818c2ead1a8944fbddf2197fd3453).
* Example logs from this workflow are available [here](https://github.com/H0R5E/MHKiT-MATLAB/actions/workflows/unit_tests.yml).

### CODE REVIEW

**Review by Matthew-Boyd — APPROVED** [review]
This is real great Mat, thanks for figuring this out for us. I see the couple key things you solved, and thanks also for everything else. Filling in the remaining blanks in the workflow and fixing the causes of the slow tests--that's a nice touch that's much appreciated.

I'm glad to see they've added macOS and Windows support! I'll keep an eye on your submitted Windows Issue; hopefully they get that resolved.

**Comment by Matthew-Boyd** [comment]
> @Matthew-Boyd, no problem, glad I could be of help. I've spent enough time banging my head against the wall with these MATLAB CI runners to know their foibles by now, but it still took me longer to do than I anticipated!
> 
> I'm hoping someone will be able to address the Windows issue soon. Generally, it doesn't take too long for MathWorks to respond - although a fix can be further down the line.
> 
> Just a reminder that I had to skip the tests for the `environmental_contour` function. I wasn't sure if you guys were aware it is broken or not.

You saved me some additional head trauma, so thanks!

Understood about the `environmental_contour` function--we'll look into it.

**Comment by tacaswell** [comment]
@H0R5E Did you tag the right Matplotlib issue?  The code implicated by https://github.com/matplotlib/matplotlib/issues/22378 goes back to mpl 2.1

**Comment by H0R5E** [comment]
@tacaswell, thanks for your comment. I think you are right, in that pinning the version of matplotlib `<3.4.2` is totally coincidental. The bug I am getting is actually really hard to recreate. I have one MATLAB session open outside of my Python environment, with an editor and a plot window open, and then a MATLAB session open with an editor window open. Then when I run the MHKIT-MATLAB tests I get this:

```MATLAB 
   ---------
    Error ID:
    ---------
    'MATLAB:Python:PyException'
    --------------
    Error Details:
    --------------
    Error using _backend_tk><module> (line 24)
    Python Error: RuntimeError: Failed to load Tcl_SetVar
    
    Error in backend_tkagg><module> (line 1)
    
    Error in __init__>import_module (line 127)
    
    Error in pyplot>backend_mod (line 268)
    
    Error in pyplot>switch_backend (line 267)
    
    Error in pyplot>switch_backend (line 247)
    
    Error in __init__>__getitem__ (line 672)
    
    Error in pyplot><module> (line 2230)
    
    Error in graphics><module> (line 4)
    
    Error in __init__><module> (line 3)
    
    Error in __init__><module> (line 1)
    
    Error in <frozen importlib>_call_with_frames_removed (line 219)
    
    Error in <frozen importlib>exec_module (line 728)
    
    Error in <frozen importlib>_load_unlocked (line 677)
    
    Error in <frozen importlib>_find_and_load_unlocked (line 967)
    
    Error in <frozen importlib>_find_and_load (line 983)
    
    Error in <frozen importlib>_gcd_import (line 1006)
    
    Error in __init__>import_module (line 127)
```

My assumption is that this is due to https://github.com/matplotlib/matplotlib/issues/22378, but I'm guessing that my remedy is bogus.

@Matthew-Boyd, @rpauly18, @ssolson I am going to put in a PR to delete the pinning of matplotlib in the workflow, as this seems like a edgy case in Windows that we are not testing now anyway.

**Comment by H0R5E** [comment]
Please see #81.

**Comment by tacaswell** [comment]
Can you test if https://github.com/matplotlib/matplotlib/pull/22445 fixes the problem for you?

**Comment by tacaswell** [comment]
And in the contexts of your use of Matplotlib inside of MATLAB code, do you actually want to be be using a GUI toolkit?

**Pull request merged**
